version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test-ui:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            nvm install 12
            npm install
            npm test
          working_directory: ./audiomnia

workflows:
  test:
    jobs:
      - test-ui
