version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  lint-css:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            nvm install 12
            npx csslint css
          working_directory: ./audiomnia
  lint-html:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            nvm install 12
            python -m SimpleHTTPServer &
            npx html-lint localhost:8080
          working_directory: ./audiomnia
  lint-js:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            nvm install 12
            npx standard
          working_directory: ./audiomnia
  lint-python:
    docker:
      - image:  cimg/python:3.8
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            make venv
            . venv/bin/activate; flake8 scrapers
          working_directory: ./audiomnia
  test-ui:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            source ~/.bashrc
            nvm install 12
            npm install
            npm test
          working_directory: ./audiomnia

workflows:
  test:
    jobs:
      - lint-css
      - lint-js
      - lint-html
      - lint-python
      - test-ui:
          requires:
            - lint-css
            - lint-js
            - lint-html
            - lint-python
