version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  lint-css:
    docker:
      - image: cimg/node:lts
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            npx csslint css
          working_directory: ./audiomnia
  lint-html:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            python -m http.server &
            npm install phantomjs-prebuilt
            npx html-lint localhost:8080
          working_directory: ./audiomnia
  lint-js:
    docker:
      - image: cimg/node:lts
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            npx standard
          working_directory: ./audiomnia
  lint-python:
    docker:
      - image:  cimg/python:3.8
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            make venv
            . venv/bin/activate; flake8 scrapers
          working_directory: ./audiomnia
  test-ui:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - run: git clone https://github.com/audiomnia/audiomnia
      - run:
          command: git checkout $CIRCLE_BRANCH
          working_directory: ./audiomnia
      - run:
          command: |
            npm install
            npm test
          working_directory: ./audiomnia

workflows:
  test:
    jobs:
      - lint-css
      - lint-js
      - lint-html
      - lint-python
      - test-ui:
          requires:
            - lint-css
            - lint-js
            - lint-html
            - lint-python
